const rudrakshaList = [
  {
    name: "1 Mukhi Rudraksha",
    mukhi: 1,
    sanskritName: "Ek Mukhi",
    deity: "Lord Shiva",
    rulingPlanet: "Sun",
    element: "Fire",
    chakra: "Crown Chakra",
    benefits: [
      "Spiritual growth",
      "Meditation",
      "Mental clarity",
      "Self-realization",
    ],
    suitableFor: ["Meditation", "Spiritual practice"],
    beadShape: "Half Moon / Crescent",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "2 Mukhi Rudraksha",
    mukhi: 2,
    sanskritName: "Dwi Mukhi",
    deity: "Ardhanarishvara",
    rulingPlanet: "Moon",
    element: "Water",
    chakra: "Heart Chakra",
    benefits: [
      "Harmony",
      "Emotional balance",
      "Relationship harmony",
      "Mental peace",
    ],
    suitableFor: ["Couples", "Relationships", "Emotional balance"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "3 Mukhi Rudraksha",
    mukhi: 3,
    sanskritName: "Tri Mukhi",
    deity: "Agni",
    rulingPlanet: "Mars",
    element: "Fire",
    chakra: "Solar Plexus Chakra",
    benefits: [
      "Removes negativity",
      "Confidence",
      "Courage",
      "Self-esteem",
    ],
    suitableFor: ["Confidence", "Personal growth"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "4 Mukhi Rudraksha",
    mukhi: 4,
    sanskritName: "Chatur Mukhi",
    deity: "Lord Brahma",
    rulingPlanet: "Mercury",
    element: "Air",
    chakra: "Throat Chakra",
    benefits: [
      "Knowledge",
      "Memory",
      "Creativity",
      "Communication",
    ],
    suitableFor: ["Students", "Teachers", "Professionals"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "5 Mukhi Rudraksha",
    mukhi: 5,
    sanskritName: "Pancha Mukhi",
    deity: "Kalagni Rudra",
    rulingPlanet: "Jupiter",
    element: "Ether",
    chakra: "All Chakras",
    benefits: [
      "Peace",
      "Meditation",
      "Spiritual growth",
      "Mental balance",
    ],
    suitableFor: ["Daily wear", "Meditation", "Beginners"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "6 Mukhi Rudraksha",
    mukhi: 6,
    sanskritName: "Shat Mukhi",
    deity: "Lord Kartikeya",
    rulingPlanet: "Venus",
    element: "Fire",
    chakra: "Root Chakra",
    benefits: [
      "Focus",
      "Discipline",
      "Confidence",
      "Emotional stability",
    ],
    suitableFor: ["Students", "Professionals"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "7 Mukhi Rudraksha",
    mukhi: 7,
    sanskritName: "Sapta Mukhi",
    deity: "Goddess Mahalakshmi",
    rulingPlanet: "Saturn",
    element: "Earth",
    chakra: "Root Chakra",
    benefits: [
      "Prosperity",
      "Financial stability",
      "Confidence",
      "Overcoming obstacles",
    ],
    suitableFor: ["Business", "Professionals", "Financial goals"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "8 Mukhi Rudraksha",
    mukhi: 8,
    sanskritName: "Ashta Mukhi",
    deity: "Lord Ganesha",
    rulingPlanet: "Rahu",
    element: "Earth",
    chakra: "Root Chakra",
    benefits: [
      "Removes obstacles",
      "Success",
      "Wisdom",
      "New opportunities",
    ],
    suitableFor: ["Business", "Entrepreneurs", "Career"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "9 Mukhi Rudraksha",
    mukhi: 9,
    sanskritName: "Nava Mukhi",
    deity: "Goddess Durga",
    rulingPlanet: "Ketu",
    element: "Fire",
    chakra: "Root Chakra",
    benefits: [
      "Courage",
      "Fearlessness",
      "Energy",
      "Protection",
    ],
    suitableFor: ["Leadership", "Protection", "Spiritual practice"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "10 Mukhi Rudraksha",
    mukhi: 10,
    sanskritName: "Dash Mukhi",
    deity: "Lord Vishnu",
    rulingPlanet: "All Planets",
    element: "Ether",
    chakra: "All Chakras",
    benefits: [
      "Protection",
      "Mental peace",
      "Negative energy protection",
      "Spiritual growth",
    ],
    suitableFor: ["Protection", "Meditation", "Daily wear"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "11 Mukhi Rudraksha",
    mukhi: 11,
    sanskritName: "Ekadash Mukhi",
    deity: "Lord Hanuman",
    rulingPlanet: "Jupiter",
    element: "Fire",
    chakra: "Crown Chakra",
    benefits: [
      "Courage",
      "Strength",
      "Confidence",
      "Protection",
    ],
    suitableFor: ["Leadership", "Spiritual practice", "Protection"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "12 Mukhi Rudraksha",
    mukhi: 12,
    sanskritName: "Dwadash Mukhi",
    deity: "Lord Surya",
    rulingPlanet: "Sun",
    element: "Fire",
    chakra: "Solar Plexus Chakra",
    benefits: [
      "Leadership",
      "Confidence",
      "Energy",
      "Success",
    ],
    suitableFor: ["Leaders", "Business", "Professionals"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "13 Mukhi Rudraksha",
    mukhi: 13,
    sanskritName: "Trayodash Mukhi",
    deity: "Lord Indra / Kamadeva",
    rulingPlanet: "Venus",
    element: "Water",
    chakra: "Sacral Chakra",
    benefits: [
      "Attraction",
      "Confidence",
      "Creativity",
      "Success",
    ],
    suitableFor: ["Business", "Relationships", "Personal growth"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "14 Mukhi Rudraksha",
    mukhi: 14,
    sanskritName: "Chaturdasha Mukhi",
    deity: "Lord Hanuman / Lord Shiva",
    rulingPlanet: "Saturn",
    element: "Earth",
    chakra: "Root Chakra",
    benefits: [
      "Intuition",
      "Protection",
      "Courage",
      "Decision making",
    ],
    suitableFor: ["Leadership", "Decision makers", "Spiritual practice"],
    beadShape: "Round",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Rudraksha",
  },

  {
    name: "Gauri Shankar Rudraksha",
    mukhi: 2,
    sanskritName: "Gauri Shankar",
    deity: "Lord Shiva and Goddess Parvati",
    rulingPlanet: "Moon",
    element: "Water",
    chakra: "Heart Chakra",
    benefits: [
      "Relationship harmony",
      "Peace",
      "Meditation",
      "Spiritual growth",
    ],
    suitableFor: ["Couples", "Meditation", "Spiritual practice"],
    beadShape: "Naturally Joined Two Beads",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Special Rudraksha",
  },

  {
    name: "Ganesha Rudraksha",
    mukhi: null,
    sanskritName: "Ganesha Rudraksha",
    deity: "Lord Ganesha",
    rulingPlanet: null,
    element: "Earth",
    chakra: "Root Chakra",
    benefits: [
      "Removing obstacles",
      "Success",
      "Wisdom",
      "New beginnings",
    ],
    suitableFor: ["Business", "Career", "New ventures"],
    beadShape: "Trunk-like Natural Projection",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Special Rudraksha",
  },

  {
    name: "Garbh Gauri Rudraksha",
    mukhi: null,
    sanskritName: "Garbh Gauri",
    deity: "Goddess Parvati",
    rulingPlanet: null,
    element: "Water",
    chakra: "Sacral Chakra",
    benefits: [
      "Family harmony",
      "Mother-child relationship",
      "Peace",
      "Spiritual growth",
    ],
    suitableFor: ["Family", "Meditation"],
    beadShape: "Naturally Joined Beads",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Special Rudraksha",
  },

  {
    name: "Savitri Rudraksha",
    mukhi: null,
    sanskritName: "Savitri",
    deity: "Goddess Savitri",
    rulingPlanet: null,
    element: "Water",
    chakra: "Heart Chakra",
    benefits: [
      "Harmony",
      "Family peace",
      "Spiritual growth",
      "Emotional balance",
    ],
    suitableFor: ["Family", "Spiritual practice"],
    beadShape: "Naturally Joined Beads",
    color: ["Brown", "Dark Brown"],
    origin: ["Nepal", "Indonesia"],
    category: "Special Rudraksha",
  },
];

export default rudrakshaList;